name: macos_secure_bookmarks
description: Flutter desktop plugin for managing secure bookmarks to access files in sandbox.
version: 0.1.1
homepage: https://github.com/authpass/macos_secure_bookmarks

flutter:
  plugin:
    platforms:
      macos:
        pluginClass: SecureBookmarksPlugin

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  logging: ">=0.10.0 <1.0.0"
  logging_appenders: ">=0.2.0 <1.0.0"

